name: 'Commit Times Daily Bot'

on:
  schedule:
    - cron: '0 12 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    name: A job to gain sum of github commits today
    steps:
      - name: gain sum of github commits today
        uses: yiliang114/commit-times@master
        id: commit
        with:
          username: 'yiliang114'
      - name: Get the output sum
        run: echo "Today ${{ steps.commit.outputs.username }} has committed ${{ steps.commit.outputs.sum }} times."
      - name: Wechat Work Robot Message
        uses: fifsky/wechat-work-action@v0.0.1
        with:
          url: ${{ secrets.WECHATWORK_WEBHOOK}}
          type: markdown
          content: |
            Today ${{ steps.commit.outputs.username }} has committed ${{ steps.commit.outputs.sum }} times.
