name: 'GitHub Actions Weather Bot'

on:
  push:
  schedule:
    - cron: '0 21 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    name: A job to gain sum of github commits today
    steps:
      - name: gain sum of github commits today
        uses: yiliang114/commit times@v0.1.3
        id: commit
        with:
          username: 'yiliang114'
      - name: Get the output sum
        run: echo "Today ${{ steps.test.outputs.username }} has committed ${{ steps.test.outputs.sum }} times."
      - name: Wechat Work Robot Message
        uses: fifsky/wechat-work-action@v0.0.1
        with:
          url: ${{ secrets.WECHATWORK_WEBHOOK}}
          type: markdown
          content: |
            Today ${{ steps.test.outputs.username }} has committed ${{ steps.test.outputs.sum }} times.
