name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and test
        run: |
          npm install
          npm run build
      - name: Wechat Work Robot Message
        uses: fifsky/wechat-work-action@v0.0.1
        with:
          url: ${{ secrets.WECHATWORK_WEBHOOK}}
          type: markdown
          content: |
            # Tips
            ## Hello
            > from github action message
            > ^_^
            - repository: ${{ github.repository }}
            - committer: ${{ github.actor }}
            - compare: [view](${{ github.event.compare }})
            - job status: ${{ job.status }}
