name: 'pkg-version demo'

on: push

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: pkg-version
        id: pkgVersion
        uses: yiliang114/pkg-version@latest

      - name: Wechat Work Robot Message
        uses: fifsky/wechat-work-action@v0.0.1
        with:
          url: ${{ secrets.WECHATWORK_WEBHOOK}}
          type: markdown
          content: |
            pkg-version action version: ${{ steps.commit.pkgVersion.version }}
